var searchData=
[
  ['danish_803',['Danish',['https://doc.qt.io/qt-5/qlocale.html#Language-enum',1,'QLocale']]],
  ['darkblue_804',['darkBlue',['https://doc.qt.io/qt-5/qt.html#GlobalColor-enum',1,'Qt']]],
  ['darkcyan_805',['darkCyan',['https://doc.qt.io/qt-5/qt.html#GlobalColor-enum',1,'Qt']]],
  ['darkgray_806',['darkGray',['https://doc.qt.io/qt-5/qt.html#GlobalColor-enum',1,'Qt']]],
  ['darkgreen_807',['darkGreen',['https://doc.qt.io/qt-5/qt.html#GlobalColor-enum',1,'Qt']]],
  ['darkmagenta_808',['darkMagenta',['https://doc.qt.io/qt-5/qt.html#GlobalColor-enum',1,'Qt']]],
  ['darkred_809',['darkRed',['https://doc.qt.io/qt-5/qt.html#GlobalColor-enum',1,'Qt']]],
  ['darkyellow_810',['darkYellow',['https://doc.qt.io/qt-5/qt.html#GlobalColor-enum',1,'Qt']]],
  ['dashdotdotline_811',['DashDotDotLine',['https://doc.qt.io/qt-5/qt.html#PenStyle-enum',1,'Qt']]],
  ['dashdotline_812',['DashDotLine',['https://doc.qt.io/qt-5/qt.html#PenStyle-enum',1,'Qt']]],
  ['dashline_813',['DashLine',['https://doc.qt.io/qt-5/qt.html#PenStyle-enum',1,'Qt']]],
  ['data_814',['data',['https://doc.qt.io/qt-5/qsortfilterproxymodel.html#data',1,'QSortFilterProxyModel::data()'],['https://doc.qt.io/qt-5/qabstractproxymodel.html#data',1,'QAbstractProxyModel::data()'],['https://doc.qt.io/qt-5/qstring.html#data',1,'QString::data()'],['https://doc.qt.io/qt-5/qstring.html#data-1',1,'QString::data() const const'],['https://doc.qt.io/qt-5/qstringlistmodel.html#data',1,'QStringListModel::data()'],['https://doc.qt.io/qt-5/qstringref.html#data',1,'QStringRef::data()'],['https://doc.qt.io/qt-5/qstringview.html#data',1,'QStringView::data()'],['https://doc.qt.io/qt-5/qvarlengtharray.html#data',1,'QVarLengthArray::data()'],['https://doc.qt.io/qt-5/qvarlengtharray.html#data-1',1,'QVarLengthArray::data() const const'],['https://doc.qt.io/qt-5/qvector.html#data',1,'QVector::data()'],['https://doc.qt.io/qt-5/qvector.html#data-1',1,'QVector::data() const const'],['https://doc.qt.io/qt-5/qweakpointer-obsolete.html#data',1,'QWeakPointer::data()'],['https://doc.qt.io/qt-5/qlatin1string.html#data',1,'QLatin1String::data()'],['https://doc.qt.io/qt-5/qexplicitlyshareddatapointer.html#data',1,'QExplicitlySharedDataPointer::data()'],['https://doc.qt.io/qt-5/qgenericargument.html#data',1,'QGenericArgument::data()'],['https://doc.qt.io/qt-5/qconcatenatetablesproxymodel.html#data',1,'QConcatenateTablesProxyModel::data()'],['https://doc.qt.io/qt-5/qbytearray.html#data-1',1,'QByteArray::data() const const'],['https://doc.qt.io/qt-5/qbytearray.html#data',1,'QByteArray::data()'],['https://doc.qt.io/qt-5/qbuffer.html#data',1,'QBuffer::data()'],['https://doc.qt.io/qt-5/qabstractitemmodel.html#data',1,'QAbstractItemModel::data()'],['https://doc.qt.io/qt-5/qsharedpointer.html#data',1,'QSharedPointer::data()'],['https://doc.qt.io/qt-5/qmimedata.html#data',1,'QMimeData::data()'],['https://doc.qt.io/qt-5/qmodelindex.html#data',1,'QModelIndex::data()'],['https://doc.qt.io/qt-5/qpersistentmodelindex.html#data',1,'QPersistentModelIndex::data()'],['https://doc.qt.io/qt-5/qpointer.html#data',1,'QPointer::data()'],['https://doc.qt.io/qt-5/qresource.html#data',1,'QResource::data()'],['https://doc.qt.io/qt-5/qscopedpointer.html#data',1,'QScopedPointer::data()'],['https://doc.qt.io/qt-5/qshareddatapointer.html#data',1,'QSharedDataPointer::data()'],['https://doc.qt.io/qt-5/qshareddatapointer.html#data-1',1,'QSharedDataPointer::data() const const'],['https://doc.qt.io/qt-5/qsharedmemory.html#data',1,'QSharedMemory::data()'],['https://doc.qt.io/qt-5/qsharedmemory.html#data-1',1,'QSharedMemory::data() const const']]],
  ['datachanged_815',['dataChanged',['https://doc.qt.io/qt-5/qabstractitemmodel.html#dataChanged',1,'QAbstractItemModel']]],
  ['datalocation_816',['DataLocation',['https://doc.qt.io/qt-5/qstandardpaths.html#StandardLocation-enum',1,'QStandardPaths']]],
  ['datapath_817',['DataPath',['https://doc.qt.io/qt-5/qlibraryinfo.html#LibraryLocation-enum',1,'QLibraryInfo']]],
  ['datasizebase1000_818',['DataSizeBase1000',['https://doc.qt.io/qt-5/qlocale.html#DataSizeFormat-enum',1,'QLocale']]],
  ['datasizeformat_819',['DataSizeFormat',['https://doc.qt.io/qt-5/qlocale.html#DataSizeFormat-enum',1,'QLocale']]],
  ['datasizeformats_820',['DataSizeFormats',['https://doc.qt.io/qt-5/qlocale.html#DataSizeFormat-enum',1,'QLocale']]],
  ['datasizeiecformat_821',['DataSizeIecFormat',['https://doc.qt.io/qt-5/qlocale.html#DataSizeFormat-enum',1,'QLocale']]],
  ['datasizesiformat_822',['DataSizeSIFormat',['https://doc.qt.io/qt-5/qlocale.html#DataSizeFormat-enum',1,'QLocale']]],
  ['datasizesiquantifiers_823',['DataSizeSIQuantifiers',['https://doc.qt.io/qt-5/qlocale.html#DataSizeFormat-enum',1,'QLocale']]],
  ['datasizetraditionalformat_824',['DataSizeTraditionalFormat',['https://doc.qt.io/qt-5/qlocale.html#DataSizeFormat-enum',1,'QLocale']]],
  ['datatoolarge_825',['DataTooLarge',['https://doc.qt.io/qt-5/qcborerror.html#Code-enum',1,'QCborError']]],
  ['datavalidation_826',['DataValidation',['https://doc.qt.io/qt-5/qjsondocument.html#DataValidation-enum',1,'QJsonDocument']]],
  ['date_827',['Date',['https://doc.qt.io/qt-5/qvariant-obsolete.html#Type-enum',1,'QVariant']]],
  ['date_828',['date',['https://doc.qt.io/qt-5/qdatetime.html#date',1,'QDateTime']]],
  ['dateformat_829',['dateFormat',['https://doc.qt.io/qt-5/qlocale.html#dateFormat',1,'QLocale']]],
  ['dateformat_830',['DateFormat',['https://doc.qt.io/qt-5/qdate.html#MonthNameType-enum',1,'QDate::DateFormat()'],['https://doc.qt.io/qt-5/qt.html#DateFormat-enum',1,'Qt::DateFormat()']]],
  ['datefromparts_831',['dateFromParts',['https://doc.qt.io/qt-5/qcalendar.html#dateFromParts-1',1,'QCalendar::dateFromParts(const QCalendar::YearMonthDay &amp;parts) const const'],['https://doc.qt.io/qt-5/qcalendar.html#dateFromParts',1,'QCalendar::dateFromParts(int year, int month, int day) const const']]],
  ['datetime_832',['DateTime',['https://doc.qt.io/qt-5/qvariant-obsolete.html#Type-enum',1,'QVariant::DateTime()'],['https://doc.qt.io/qt-5/qcborvalue.html#Type-enum',1,'QCborValue::DateTime()']]],
  ['datetimeformat_833',['dateTimeFormat',['https://doc.qt.io/qt-5/qlocale.html#dateTimeFormat',1,'QLocale']]],
  ['datetimetostring_834',['dateTimeToString',['https://doc.qt.io/qt-5/qcalendar.html#dateTimeToString',1,'QCalendar']]],
  ['day_835',['day',['https://doc.qt.io/qt-5/qdate.html#day',1,'QDate::day(QCalendar cal) const const'],['https://doc.qt.io/qt-5/qdate.html#day-1',1,'QDate::day() const const']]],
  ['daylighttime_836',['DaylightTime',['https://doc.qt.io/qt-5/qtimezone.html#TimeType-enum',1,'QTimeZone']]],
  ['daylighttimeoffset_837',['daylightTimeOffset',['https://doc.qt.io/qt-5/qtimezone.html#daylightTimeOffset',1,'QTimeZone']]],
  ['dayname_838',['dayName',['https://doc.qt.io/qt-5/qlocale.html#dayName',1,'QLocale']]],
  ['dayofweek_839',['dayOfWeek',['https://doc.qt.io/qt-5/qcalendar.html#dayOfWeek',1,'QCalendar::dayOfWeek()'],['https://doc.qt.io/qt-5/qdate.html#dayOfWeek-1',1,'QDate::dayOfWeek() const const'],['https://doc.qt.io/qt-5/qdate.html#dayOfWeek',1,'QDate::dayOfWeek(QCalendar cal) const const']]],
  ['dayofweek_840',['DayOfWeek',['https://doc.qt.io/qt-5/qt.html#DayOfWeek-enum',1,'Qt']]],
  ['dayofyear_841',['dayOfYear',['https://doc.qt.io/qt-5/qdate.html#dayOfYear-1',1,'QDate::dayOfYear() const const'],['https://doc.qt.io/qt-5/qdate.html#dayOfYear',1,'QDate::dayOfYear(QCalendar cal) const const']]],
  ['daysinmonth_842',['daysInMonth',['https://doc.qt.io/qt-5/qdate.html#daysInMonth-1',1,'QDate::daysInMonth() const const'],['https://doc.qt.io/qt-5/qdate.html#daysInMonth',1,'QDate::daysInMonth(QCalendar cal) const const'],['https://doc.qt.io/qt-5/qcalendar.html#daysInMonth',1,'QCalendar::daysInMonth()']]],
  ['daysinyear_843',['daysInYear',['https://doc.qt.io/qt-5/qdate.html#daysInYear',1,'QDate::daysInYear(QCalendar cal) const const'],['https://doc.qt.io/qt-5/qdate.html#daysInYear-1',1,'QDate::daysInYear() const const'],['https://doc.qt.io/qt-5/qcalendar.html#daysInYear',1,'QCalendar::daysInYear()']]],
  ['daysto_844',['daysTo',['https://doc.qt.io/qt-5/qdatetime.html#daysTo',1,'QDateTime::daysTo()'],['https://doc.qt.io/qt-5/qdate.html#daysTo',1,'QDate::daysTo()']]],
  ['dbusmenu_845',['dbusmenu',['../classcom_1_1canonical_1_1dbusmenu.html',1,'com::canonical']]],
  ['dbusmenuexporter_846',['DBusMenuExporter',['../classDBusMenuExporter.html',1,'DBusMenuExporter'],['../classDBusMenuExporter.html#a5f7beacff5f22bb2443d08354dafd3b4',1,'DBusMenuExporter::DBusMenuExporter()']]],
  ['dbusmenuimporter_847',['DBusMenuImporter',['../classDBusMenuImporter.html',1,'DBusMenuImporter'],['../classDBusMenuImporter.html#a01e4d5bfde821a8e8c13d31aadf23a73',1,'DBusMenuImporter::DBusMenuImporter(const QString &amp;service, const QString &amp;path, QObject *parent=nullptr)'],['../classDBusMenuImporter.html#a11d5c43e2a4774ded80092174141a682',1,'DBusMenuImporter::DBusMenuImporter(const QString &amp;service, const QString &amp;path, DBusMenuImporterType type, QObject *parent=nullptr)']]],
  ['dce_848',['DCE',['https://doc.qt.io/qt-5/quuid.html#Variant-enum',1,'QUuid']]],
  ['deactivatecontrol_849',['DeactivateControl',['https://doc.qt.io/qt-5/qevent.html#Type-enum',1,'QEvent']]],
  ['deadline_850',['deadline',['https://doc.qt.io/qt-5/qdeadlinetimer.html#deadline',1,'QDeadlineTimer']]],
  ['deadlinensecs_851',['deadlineNSecs',['https://doc.qt.io/qt-5/qdeadlinetimer.html#deadlineNSecs',1,'QDeadlineTimer']]],
  ['debug_852',['debug',['https://doc.qt.io/qt-5/qmessagelogger.html#debug-5',1,'QMessageLogger::debug(QMessageLogger::CategoryFunction catFunc) const const'],['https://doc.qt.io/qt-5/qmessagelogger.html#debug-4',1,'QMessageLogger::debug(const QLoggingCategory &amp;cat) const const'],['https://doc.qt.io/qt-5/qmessagelogger.html#debug-3',1,'QMessageLogger::debug() const const'],['https://doc.qt.io/qt-5/qmessagelogger.html#debug',1,'QMessageLogger::debug(const char *msg,...) const const'],['https://doc.qt.io/qt-5/qmessagelogger.html#debug-1',1,'QMessageLogger::debug(const QLoggingCategory &amp;cat, const char *msg,...) const const'],['https://doc.qt.io/qt-5/qmessagelogger.html#debug-2',1,'QMessageLogger::debug(QMessageLogger::CategoryFunction catFunc, const char *msg,...) const const']]],
  ['debugstream_853',['debugStream',['https://doc.qt.io/qt-5/qmetatype.html#debugStream',1,'QMetaType']]],
  ['dec_854',['dec',['https://doc.qt.io/qt-5/qt.html#dec',1,'Qt']]],
  ['decimalpoint_855',['decimalPoint',['https://doc.qt.io/qt-5/qlocale.html#decimalPoint',1,'QLocale']]],
  ['decodedmode_856',['DecodedMode',['https://doc.qt.io/qt-5/qurl.html#ParsingMode-enum',1,'QUrl']]],
  ['decodename_857',['decodeName',['https://doc.qt.io/qt-5/qfile.html#decodeName-1',1,'QFile::decodeName(const char *localFileName)'],['https://doc.qt.io/qt-5/qfile.html#decodeName',1,'QFile::decodeName(const QByteArray &amp;localFileName)']]],
  ['decodereserved_858',['DecodeReserved',['https://doc.qt.io/qt-5/qurl.html#ComponentFormattingOption-enum',1,'QUrl']]],
  ['decoderfn_859',['DecoderFn',['https://doc.qt.io/qt-5/qfile.html#DecoderFn-typedef',1,'QFile']]],
  ['decomposition_860',['Decomposition',['https://doc.qt.io/qt-5/qchar.html#Decomposition-enum',1,'QChar']]],
  ['decomposition_861',['decomposition',['https://doc.qt.io/qt-5/qchar.html#decomposition-1',1,'QChar::decomposition(uint ucs4)'],['https://doc.qt.io/qt-5/qchar.html#decomposition',1,'QChar::decomposition() const const']]],
  ['decompositiontag_862',['decompositionTag',['https://doc.qt.io/qt-5/qchar.html#decompositionTag-1',1,'QChar::decompositionTag(uint ucs4)'],['https://doc.qt.io/qt-5/qchar.html#decompositionTag',1,'QChar::decompositionTag() const const']]],
  ['decorationpropertyrole_863',['DecorationPropertyRole',['https://doc.qt.io/qt-5/qt.html#ItemDataRole-enum',1,'Qt']]],
  ['decorationrole_864',['DecorationRole',['https://doc.qt.io/qt-5/qt.html#ItemDataRole-enum',1,'Qt']]],
  ['deepbindhint_865',['DeepBindHint',['https://doc.qt.io/qt-5/qlibrary.html#LoadHint-enum',1,'QLibrary']]],
  ['deephistory_866',['DeepHistory',['https://doc.qt.io/qt-5/qhistorystate.html#HistoryType-enum',1,'QHistoryState']]],
  ['deepnesting_867',['DeepNesting',['https://doc.qt.io/qt-5/qjsonparseerror.html#ParseError-enum',1,'QJsonParseError']]],
  ['defaultanimations_868',['defaultAnimations',['https://doc.qt.io/qt-5/qstatemachine.html#defaultAnimations',1,'QStateMachine']]],
  ['defaultcategory_869',['defaultCategory',['https://doc.qt.io/qt-5/qloggingcategory.html#defaultCategory',1,'QLoggingCategory']]],
  ['defaultcodec_870',['DefaultCodec',['https://doc.qt.io/qt-5/qcoreapplication-obsolete.html#Encoding-enum',1,'QCoreApplication']]],
  ['defaultcontextmenu_871',['DefaultContextMenu',['https://doc.qt.io/qt-5/qt.html#ContextMenuPolicy-enum',1,'Qt']]],
  ['defaultconversion_872',['DefaultConversion',['https://doc.qt.io/qt-5/qtextcodec.html#ConversionFlag-enum',1,'QTextCodec']]],
  ['defaultformat_873',['defaultFormat',['https://doc.qt.io/qt-5/qsettings.html#defaultFormat',1,'QSettings']]],
  ['defaultlocalelongdate_874',['DefaultLocaleLongDate',['https://doc.qt.io/qt-5/qt.html#DateFormat-enum',1,'Qt']]],
  ['defaultlocaleshortdate_875',['DefaultLocaleShortDate',['https://doc.qt.io/qt-5/qt.html#DateFormat-enum',1,'Qt']]],
  ['defaultname_876',['DefaultName',['https://doc.qt.io/qt-5/qtimezone.html#NameType-enum',1,'QTimeZone']]],
  ['defaultnumberoptions_877',['DefaultNumberOptions',['https://doc.qt.io/qt-5/qlocale.html#NumberOption-enum',1,'QLocale']]],
  ['defaultquerypairdelimiter_878',['defaultQueryPairDelimiter',['https://doc.qt.io/qt-5/qurlquery.html#defaultQueryPairDelimiter',1,'QUrlQuery']]],
  ['defaultqueryvaluedelimiter_879',['defaultQueryValueDelimiter',['https://doc.qt.io/qt-5/qurlquery.html#defaultQueryValueDelimiter',1,'QUrlQuery']]],
  ['defaultresolution_880',['DefaultResolution',['https://doc.qt.io/qt-5/qurl.html#UserInputResolutionOption-enum',1,'QUrl']]],
  ['defaultstate_881',['defaultState',['https://doc.qt.io/qt-5/qhistorystate.html#defaultState',1,'QHistoryState::defaultState() const const'],['https://doc.qt.io/qt-5/qhistorystate.html#defaultState-prop',1,'QHistoryState::defaultState()']]],
  ['defaultstatechanged_882',['defaultStateChanged',['https://doc.qt.io/qt-5/qhistorystate.html#defaultStateChanged',1,'QHistoryState']]],
  ['defaulttransition_883',['defaultTransition',['https://doc.qt.io/qt-5/qhistorystate.html#defaultTransition',1,'QHistoryState::defaultTransition() const const'],['https://doc.qt.io/qt-5/qhistorystate.html#defaultTransition-prop',1,'QHistoryState::defaultTransition()']]],
  ['defaulttransitionchanged_884',['defaultTransitionChanged',['https://doc.qt.io/qt-5/qhistorystate.html#defaultTransitionChanged',1,'QHistoryState']]],
  ['defaultvalues_885',['defaultValues',['https://doc.qt.io/qt-5/qcommandlineoption.html#defaultValues',1,'QCommandLineOption']]],
  ['defaultverbosity_886',['DefaultVerbosity',['https://doc.qt.io/qt-5/qdebug.html#VerbosityLevel-enum',1,'QDebug']]],
  ['deferreddelete_887',['DeferredDelete',['https://doc.qt.io/qt-5/qevent.html#Type-enum',1,'QEvent']]],
  ['deletelater_888',['deleteLater',['https://doc.qt.io/qt-5/qobject.html#deleteLater',1,'QObject']]],
  ['deletewhenstopped_889',['DeleteWhenStopped',['https://doc.qt.io/qt-5/qabstractanimation.html#DeletionPolicy-enum',1,'QAbstractAnimation']]],
  ['deletionpolicy_890',['DeletionPolicy',['https://doc.qt.io/qt-5/qabstractanimation.html#DeletionPolicy-enum',1,'QAbstractAnimation']]],
  ['democraticrepublicofcongo_891',['DemocraticRepublicOfCongo',['https://doc.qt.io/qt-5/qlocale.html#Country-enum',1,'QLocale']]],
  ['democraticrepublicofkorea_892',['DemocraticRepublicOfKorea',['https://doc.qt.io/qt-5/qlocale.html#Country-enum',1,'QLocale']]],
  ['denmark_893',['Denmark',['https://doc.qt.io/qt-5/qlocale.html#Country-enum',1,'QLocale']]],
  ['dense1pattern_894',['Dense1Pattern',['https://doc.qt.io/qt-5/qt.html#BrushStyle-enum',1,'Qt']]],
  ['dense2pattern_895',['Dense2Pattern',['https://doc.qt.io/qt-5/qt.html#BrushStyle-enum',1,'Qt']]],
  ['dense3pattern_896',['Dense3Pattern',['https://doc.qt.io/qt-5/qt.html#BrushStyle-enum',1,'Qt']]],
  ['dense4pattern_897',['Dense4Pattern',['https://doc.qt.io/qt-5/qt.html#BrushStyle-enum',1,'Qt']]],
  ['dense5pattern_898',['Dense5Pattern',['https://doc.qt.io/qt-5/qt.html#BrushStyle-enum',1,'Qt']]],
  ['dense6pattern_899',['Dense6Pattern',['https://doc.qt.io/qt-5/qt.html#BrushStyle-enum',1,'Qt']]],
  ['dense7pattern_900',['Dense7Pattern',['https://doc.qt.io/qt-5/qt.html#BrushStyle-enum',1,'Qt']]],
  ['deprecated_20list_901',['Deprecated List',['../deprecated.html',1,'']]],
  ['dequeue_902',['dequeue',['https://doc.qt.io/qt-5/qqueue.html#dequeue',1,'QQueue']]],
  ['deref_903',['deref',['https://doc.qt.io/qt-5/qatomicinteger.html#deref',1,'QAtomicInteger']]],
  ['descendingorder_904',['DescendingOrder',['https://doc.qt.io/qt-5/qt.html#SortOrder-enum',1,'Qt']]],
  ['description_905',['description',['https://doc.qt.io/qt-5/qcommandlineoption.html#description',1,'QCommandLineOption']]],
  ['deselect_906',['Deselect',['https://doc.qt.io/qt-5/qitemselectionmodel.html#SelectionFlag-enum',1,'QItemSelectionModel']]],
  ['deseretscript_907',['DeseretScript',['https://doc.qt.io/qt-5/qlocale.html#Script-enum',1,'QLocale']]],
  ['desktop_908',['Desktop',['https://doc.qt.io/qt-5/qt.html#WindowType-enum',1,'Qt']]],
  ['desktoplocation_909',['DesktopLocation',['https://doc.qt.io/qt-5/qstandardpaths.html#StandardLocation-enum',1,'QStandardPaths']]],
  ['destroy_910',['destroy',['https://doc.qt.io/qt-5/qmetatype.html#destroy-1',1,'QMetaType::destroy(void *data) const const'],['https://doc.qt.io/qt-5/qmetatype.html#destroy',1,'QMetaType::destroy(int type, void *data)']]],
  ['destroy_911',['Destroy',['https://doc.qt.io/qt-5/qevent.html#Type-enum',1,'QEvent']]],
  ['destroyed_912',['destroyed',['https://doc.qt.io/qt-5/qobject.html#destroyed',1,'QObject']]],
  ['destruct_913',['destruct',['https://doc.qt.io/qt-5/qmetatype.html#destruct',1,'QMetaType::destruct(int type, void *where)'],['https://doc.qt.io/qt-5/qmetatype.html#destruct-1',1,'QMetaType::destruct(void *data) const const']]],
  ['detach_914',['detach',['https://doc.qt.io/qt-5/qexplicitlyshareddatapointer.html#detach',1,'QExplicitlySharedDataPointer::detach()'],['https://doc.qt.io/qt-5/qshareddatapointer.html#detach',1,'QSharedDataPointer::detach()'],['https://doc.qt.io/qt-5/qsharedmemory.html#detach',1,'QSharedMemory::detach()']]],
  ['devanagariscript_915',['DevanagariScript',['https://doc.qt.io/qt-5/qlocale.html#Script-enum',1,'QLocale']]],
  ['device_916',['device',['https://doc.qt.io/qt-5/qcborstreamreader.html#device',1,'QCborStreamReader::device()'],['https://doc.qt.io/qt-5/qcborstreamwriter.html#device',1,'QCborStreamWriter::device()'],['https://doc.qt.io/qt-5/qdatastream.html#device',1,'QDataStream::device()'],['https://doc.qt.io/qt-5/qstorageinfo.html#device',1,'QStorageInfo::device()'],['https://doc.qt.io/qt-5/qtextstream.html#device',1,'QTextStream::device()'],['https://doc.qt.io/qt-5/qxmlstreamreader.html#device',1,'QXmlStreamReader::device()'],['https://doc.qt.io/qt-5/qxmlstreamwriter.html#device',1,'QXmlStreamWriter::device()']]],
  ['devicecoordinates_917',['DeviceCoordinates',['https://doc.qt.io/qt-5/qt.html#CoordinateSystem-enum',1,'Qt']]],
  ['diagcrosspattern_918',['DiagCrossPattern',['https://doc.qt.io/qt-5/qt.html#BrushStyle-enum',1,'Qt']]],
  ['diagnosticnotationoption_919',['DiagnosticNotationOption',['https://doc.qt.io/qt-5/qcborvalue.html#DiagnosticNotationOption-enum',1,'QCborValue']]],
  ['diagnosticnotationoptions_920',['DiagnosticNotationOptions',['https://doc.qt.io/qt-5/qcborvalue.html#DiagnosticNotationOption-enum',1,'QCborValue']]],
  ['dialog_921',['Dialog',['https://doc.qt.io/qt-5/qt.html#WindowType-enum',1,'Qt']]],
  ['dialogexec_922',['DialogExec',['https://doc.qt.io/qt-5/qeventloop.html#ProcessEventsFlag-enum',1,'QEventLoop']]],
  ['diegogarcia_923',['DiegoGarcia',['https://doc.qt.io/qt-5/qlocale.html#Country-enum',1,'QLocale']]],
  ['difference_5ftype_924',['difference_type',['https://doc.qt.io/qt-5/qcborarray.html#difference_type-typedef',1,'QCborArray::difference_type()'],['https://doc.qt.io/qt-5/qlinkedlist.html#difference_type-typedef',1,'QLinkedList::difference_type()'],['https://doc.qt.io/qt-5/qvarlengtharray.html#difference_type-typedef',1,'QVarLengthArray::difference_type()'],['https://doc.qt.io/qt-5/qstringview.html#difference_type-typedef',1,'QStringView::difference_type()'],['https://doc.qt.io/qt-5/qstring.html#difference_type-typedef',1,'QString::difference_type()'],['https://doc.qt.io/qt-5/qset-iterator.html#difference_type-typedef',1,'QSet::iterator::difference_type()'],['https://doc.qt.io/qt-5/qset-const-iterator.html#difference_type-typedef',1,'QSet::const_iterator::difference_type()'],['https://doc.qt.io/qt-5/qset.html#difference_type-typedef',1,'QSet::difference_type()'],['https://doc.qt.io/qt-5/qmap.html#difference_type-typedef',1,'QMap::difference_type()'],['https://doc.qt.io/qt-5/qlist.html#difference_type-typedef',1,'QList::difference_type()'],['https://doc.qt.io/qt-5/qlatin1string.html#difference_type-alias',1,'QLatin1String::difference_type()'],['https://doc.qt.io/qt-5/qjsonarray.html#difference_type-typedef',1,'QJsonArray::difference_type()'],['https://doc.qt.io/qt-5/qhash.html#difference_type-typedef',1,'QHash::difference_type()'],['https://doc.qt.io/qt-5/qvector.html#difference_type-typedef',1,'QVector::difference_type()'],['https://doc.qt.io/qt-5/qfuture-const-iterator.html#difference_type-typedef',1,'QFuture::const_iterator::difference_type()']]],
  ['diffusealphadither_925',['DiffuseAlphaDither',['https://doc.qt.io/qt-5/qt.html#ImageConversionFlag-enum',1,'Qt']]],
  ['diffusedither_926',['DiffuseDither',['https://doc.qt.io/qt-5/qt.html#ImageConversionFlag-enum',1,'Qt']]],
  ['digitvalue_927',['digitValue',['https://doc.qt.io/qt-5/qchar.html#digitValue-1',1,'QChar::digitValue(uint ucs4)'],['https://doc.qt.io/qt-5/qchar.html#digitValue',1,'QChar::digitValue() const const']]],
  ['dir_928',['dir',['https://doc.qt.io/qt-5/qfileinfo.html#dir',1,'QFileInfo']]],
  ['diral_929',['DirAL',['https://doc.qt.io/qt-5/qchar.html#Direction-enum',1,'QChar']]],
  ['diran_930',['DirAN',['https://doc.qt.io/qt-5/qchar.html#Direction-enum',1,'QChar']]],
  ['dirb_931',['DirB',['https://doc.qt.io/qt-5/qchar.html#Direction-enum',1,'QChar']]],
  ['dirbn_932',['DirBN',['https://doc.qt.io/qt-5/qchar.html#Direction-enum',1,'QChar']]],
  ['dircs_933',['DirCS',['https://doc.qt.io/qt-5/qchar.html#Direction-enum',1,'QChar']]],
  ['directconnection_934',['DirectConnection',['https://doc.qt.io/qt-5/qt.html#ConnectionType-enum',1,'Qt']]],
  ['direction_935',['direction',['https://doc.qt.io/qt-5/qchar.html#direction-1',1,'QChar::direction()'],['https://doc.qt.io/qt-5/qtimeline.html#direction-prop',1,'QTimeLine::direction() const const']]],
  ['direction_936',['Direction',['https://doc.qt.io/qt-5/qtimeline.html#Direction-enum',1,'QTimeLine::Direction()'],['https://doc.qt.io/qt-5/qabstractanimation.html#Direction-enum',1,'QAbstractAnimation::Direction()'],['https://doc.qt.io/qt-5/qchar.html#Direction-enum',1,'QChar::Direction()']]],
  ['direction_937',['direction',['https://doc.qt.io/qt-5/qchar.html#direction',1,'QChar::direction()'],['https://doc.qt.io/qt-5/qabstractanimation.html#direction-prop',1,'QAbstractAnimation::direction()'],['https://doc.qt.io/qt-5/qtimeline.html#direction-prop',1,'QTimeLine::direction()'],['https://doc.qt.io/qt-5/qabstractanimation.html#direction-prop',1,'QAbstractAnimation::direction()']]],
  ['directionchanged_938',['directionChanged',['https://doc.qt.io/qt-5/qabstractanimation.html#directionChanged',1,'QAbstractAnimation']]],
  ['directories_939',['directories',['https://doc.qt.io/qt-5/qfilesystemwatcher.html#directories',1,'QFileSystemWatcher']]],
  ['directorychanged_940',['directoryChanged',['https://doc.qt.io/qt-5/qfilesystemwatcher.html#directoryChanged',1,'QFileSystemWatcher']]],
  ['directwritefallback_941',['directWriteFallback',['https://doc.qt.io/qt-5/qsavefile.html#directWriteFallback',1,'QSaveFile']]],
  ['diren_942',['DirEN',['https://doc.qt.io/qt-5/qchar.html#Direction-enum',1,'QChar']]],
  ['dires_943',['DirES',['https://doc.qt.io/qt-5/qchar.html#Direction-enum',1,'QChar']]],
  ['diret_944',['DirET',['https://doc.qt.io/qt-5/qchar.html#Direction-enum',1,'QChar']]],
  ['dirfsi_945',['DirFSI',['https://doc.qt.io/qt-5/qchar.html#Direction-enum',1,'QChar']]],
  ['dirl_946',['DirL',['https://doc.qt.io/qt-5/qchar.html#Direction-enum',1,'QChar']]],
  ['dirlre_947',['DirLRE',['https://doc.qt.io/qt-5/qchar.html#Direction-enum',1,'QChar']]],
  ['dirlri_948',['DirLRI',['https://doc.qt.io/qt-5/qchar.html#Direction-enum',1,'QChar']]],
  ['dirlro_949',['DirLRO',['https://doc.qt.io/qt-5/qchar.html#Direction-enum',1,'QChar']]],
  ['dirname_950',['dirName',['https://doc.qt.io/qt-5/qdir.html#dirName',1,'QDir']]],
  ['dirnsm_951',['DirNSM',['https://doc.qt.io/qt-5/qchar.html#Direction-enum',1,'QChar']]],
  ['diron_952',['DirON',['https://doc.qt.io/qt-5/qchar.html#Direction-enum',1,'QChar']]],
  ['dirpdf_953',['DirPDF',['https://doc.qt.io/qt-5/qchar.html#Direction-enum',1,'QChar']]],
  ['dirpdi_954',['DirPDI',['https://doc.qt.io/qt-5/qchar.html#Direction-enum',1,'QChar']]],
  ['dirr_955',['DirR',['https://doc.qt.io/qt-5/qchar.html#Direction-enum',1,'QChar']]],
  ['dirrle_956',['DirRLE',['https://doc.qt.io/qt-5/qchar.html#Direction-enum',1,'QChar']]],
  ['dirrli_957',['DirRLI',['https://doc.qt.io/qt-5/qchar.html#Direction-enum',1,'QChar']]],
  ['dirrlo_958',['DirRLO',['https://doc.qt.io/qt-5/qchar.html#Direction-enum',1,'QChar']]],
  ['dirs_959',['DirS',['https://doc.qt.io/qt-5/qchar.html#Direction-enum',1,'QChar']]],
  ['dirs_960',['Dirs',['https://doc.qt.io/qt-5/qdir.html#Filter-enum',1,'QDir']]],
  ['dirsfirst_961',['DirsFirst',['https://doc.qt.io/qt-5/qdir.html#SortFlag-enum',1,'QDir']]],
  ['dirslast_962',['DirsLast',['https://doc.qt.io/qt-5/qdir.html#SortFlag-enum',1,'QDir']]],
  ['dirws_963',['DirWS',['https://doc.qt.io/qt-5/qchar.html#Direction-enum',1,'QChar']]],
  ['discard_964',['discard',['https://doc.qt.io/qt-5/qrandomgenerator.html#discard',1,'QRandomGenerator']]],
  ['disconnect_965',['disconnect',['https://doc.qt.io/qt-5/qobject.html#disconnect',1,'QObject::disconnect(const QObject *sender, const char *signal, const QObject *receiver, const char *method)'],['https://doc.qt.io/qt-5/qobject.html#disconnect-5',1,'QObject::disconnect(const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)'],['https://doc.qt.io/qt-5/qobject.html#disconnect-4',1,'QObject::disconnect(const QMetaObject::Connection &amp;connection)'],['https://doc.qt.io/qt-5/qobject.html#disconnect-3',1,'QObject::disconnect(const QObject *receiver, const char *method) const const'],['https://doc.qt.io/qt-5/qobject.html#disconnect-2',1,'QObject::disconnect(const char *signal, const QObject *receiver, const char *method) const const'],['https://doc.qt.io/qt-5/qobject.html#disconnect-1',1,'QObject::disconnect(const QObject *sender, const QMetaMethod &amp;signal, const QObject *receiver, const QMetaMethod &amp;method)']]],
  ['disconnectnotify_966',['disconnectNotify',['https://doc.qt.io/qt-5/qobject.html#disconnectNotify',1,'QObject']]],
  ['dismiss_967',['dismiss',['https://doc.qt.io/qt-5/qscopeguard.html#dismiss',1,'QScopeGuard']]],
  ['displayname_968',['displayName',['https://doc.qt.io/qt-5/qtimezone.html#displayName',1,'QTimeZone::displayName()'],['https://doc.qt.io/qt-5/qstandardpaths.html#displayName',1,'QStandardPaths::displayName()'],['https://doc.qt.io/qt-5/qstorageinfo.html#displayName',1,'QStorageInfo::displayName()'],['https://doc.qt.io/qt-5/qtimezone.html#displayName-1',1,'QTimeZone::displayName()']]],
  ['displaypropertyrole_969',['DisplayPropertyRole',['https://doc.qt.io/qt-5/qt.html#ItemDataRole-enum',1,'Qt']]],
  ['displayrole_970',['DisplayRole',['https://doc.qt.io/qt-5/qt.html#ItemDataRole-enum',1,'Qt']]],
  ['dither_5fmask_971',['Dither_Mask',['https://doc.qt.io/qt-5/qt.html#ImageConversionFlag-enum',1,'Qt']]],
  ['dithermode_5fmask_972',['DitherMode_Mask',['https://doc.qt.io/qt-5/qt.html#ImageConversionFlag-enum',1,'Qt']]],
  ['divehi_973',['Divehi',['https://doc.qt.io/qt-5/qlocale.html#Language-enum',1,'QLocale']]],
  ['djibouti_974',['Djibouti',['https://doc.qt.io/qt-5/qlocale.html#Country-enum',1,'QLocale']]],
  ['dockwidgetarea_975',['DockWidgetArea',['https://doc.qt.io/qt-5/qt.html#DockWidgetArea-enum',1,'Qt']]],
  ['dockwidgetarea_5fmask_976',['DockWidgetArea_Mask',['https://doc.qt.io/qt-5/qt.html#DockWidgetArea-enum',1,'Qt']]],
  ['dockwidgetareas_977',['DockWidgetAreas',['https://doc.qt.io/qt-5/qt.html#DockWidgetArea-enum',1,'Qt']]],
  ['documentationpath_978',['DocumentationPath',['https://doc.qt.io/qt-5/qlibraryinfo.html#LibraryLocation-enum',1,'QLibraryInfo']]],
  ['documentencoding_979',['documentEncoding',['https://doc.qt.io/qt-5/qxmlstreamreader.html#documentEncoding',1,'QXmlStreamReader']]],
  ['documentslocation_980',['DocumentsLocation',['https://doc.qt.io/qt-5/qstandardpaths.html#StandardLocation-enum',1,'QStandardPaths']]],
  ['documenttoolarge_981',['DocumentTooLarge',['https://doc.qt.io/qt-5/qjsonparseerror.html#ParseError-enum',1,'QJsonParseError']]],
  ['documentversion_982',['documentVersion',['https://doc.qt.io/qt-5/qxmlstreamreader.html#documentVersion',1,'QXmlStreamReader']]],
  ['dogri_983',['Dogri',['https://doc.qt.io/qt-5/qlocale.html#Language-enum',1,'QLocale']]],
  ['dominica_984',['Dominica',['https://doc.qt.io/qt-5/qlocale.html#Country-enum',1,'QLocale']]],
  ['dominicanrepublic_985',['DominicanRepublic',['https://doc.qt.io/qt-5/qlocale.html#Country-enum',1,'QLocale']]],
  ['donotuseparent_986',['DoNotUseParent',['https://doc.qt.io/qt-5/qabstractitemmodel.html#CheckIndexOption-enum',1,'QAbstractItemModel']]],
  ['dontautomaticallyoptimizeoption_987',['DontAutomaticallyOptimizeOption',['https://doc.qt.io/qt-5/qregularexpression.html#PatternOption-enum',1,'QRegularExpression']]],
  ['dontcaptureoption_988',['DontCaptureOption',['https://doc.qt.io/qt-5/qregularexpression.html#PatternOption-enum',1,'QRegularExpression']]],
  ['dontchecksubjectstringmatchoption_989',['DontCheckSubjectStringMatchOption',['https://doc.qt.io/qt-5/qregularexpression.html#MatchOption-enum',1,'QRegularExpression']]],
  ['dontclosehandle_990',['DontCloseHandle',['https://doc.qt.io/qt-5/qfiledevice.html#FileHandleFlag-enum',1,'QFileDevice']]],
  ['dontrestoreproperties_991',['DontRestoreProperties',['https://doc.qt.io/qt-5/qstate.html#RestorePolicy-enum',1,'QState']]],
  ['dontstartgestureonchildren_992',['DontStartGestureOnChildren',['https://doc.qt.io/qt-5/qt.html#GestureFlag-enum',1,'Qt']]],
  ['dotline_993',['DotLine',['https://doc.qt.io/qt-5/qt.html#PenStyle-enum',1,'Qt']]],
  ['dotmatcheseverythingoption_994',['DotMatchesEverythingOption',['https://doc.qt.io/qt-5/qregularexpression.html#PatternOption-enum',1,'QRegularExpression']]],
  ['dotproduct_995',['dotProduct',['https://doc.qt.io/qt-5/qpoint.html#dotProduct',1,'QPoint::dotProduct()'],['https://doc.qt.io/qt-5/qpointf.html#dotProduct',1,'QPointF::dotProduct()']]],
  ['double_996',['Double',['https://doc.qt.io/qt-5/qcborstreamreader.html#Type-enum',1,'QCborStreamReader::Double()'],['https://doc.qt.io/qt-5/qcborvalue.html#Type-enum',1,'QCborValue::Double()'],['https://doc.qt.io/qt-5/qjsonvalue.html#Type-enum',1,'QJsonValue::Double()'],['https://doc.qt.io/qt-5/qmetatype.html#Type-enum',1,'QMetaType::Double()'],['https://doc.qt.io/qt-5/qvariant-obsolete.html#Type-enum',1,'QVariant::Double()']]],
  ['doubleprecision_997',['DoublePrecision',['https://doc.qt.io/qt-5/qdatastream.html#FloatingPointPrecision-enum',1,'QDataStream']]],
  ['downarrow_998',['DownArrow',['https://doc.qt.io/qt-5/qt.html#ArrowType-enum',1,'Qt']]],
  ['downloadlocation_999',['DownloadLocation',['https://doc.qt.io/qt-5/qstandardpaths.html#StandardLocation-enum',1,'QStandardPaths']]],
  ['dragcopycursor_1000',['DragCopyCursor',['https://doc.qt.io/qt-5/qt.html#CursorShape-enum',1,'Qt']]],
  ['dragenter_1001',['DragEnter',['https://doc.qt.io/qt-5/qevent.html#Type-enum',1,'QEvent']]],
  ['dragleave_1002',['DragLeave',['https://doc.qt.io/qt-5/qevent.html#Type-enum',1,'QEvent']]],
  ['draglinkcursor_1003',['DragLinkCursor',['https://doc.qt.io/qt-5/qt.html#CursorShape-enum',1,'Qt']]],
  ['dragmove_1004',['DragMove',['https://doc.qt.io/qt-5/qevent.html#Type-enum',1,'QEvent']]],
  ['dragmovecursor_1005',['DragMoveCursor',['https://doc.qt.io/qt-5/qt.html#CursorShape-enum',1,'Qt']]],
  ['dragresponse_1006',['DragResponse',['https://doc.qt.io/qt-5/qevent.html#Type-enum',1,'QEvent']]],
  ['drawer_1007',['Drawer',['https://doc.qt.io/qt-5/qt.html#WindowType-enum',1,'Qt']]],
  ['drives_1008',['Drives',['https://doc.qt.io/qt-5/qdir.html#Filter-enum',1,'QDir']]],
  ['drives_1009',['drives',['https://doc.qt.io/qt-5/qdir.html#drives',1,'QDir']]],
  ['drop_1010',['Drop',['https://doc.qt.io/qt-5/qevent.html#Type-enum',1,'QEvent']]],
  ['dropaction_1011',['DropAction',['https://doc.qt.io/qt-5/qt.html#DropAction-enum',1,'Qt']]],
  ['dropactions_1012',['DropActions',['https://doc.qt.io/qt-5/qt.html#DropAction-enum',1,'Qt']]],
  ['dropmimedata_1013',['dropMimeData',['https://doc.qt.io/qt-5/qabstractitemmodel.html#dropMimeData',1,'QAbstractItemModel::dropMimeData()'],['https://doc.qt.io/qt-5/qabstractlistmodel.html#dropMimeData',1,'QAbstractListModel::dropMimeData()'],['https://doc.qt.io/qt-5/qabstractproxymodel.html#dropMimeData',1,'QAbstractProxyModel::dropMimeData()'],['https://doc.qt.io/qt-5/qabstracttablemodel.html#dropMimeData',1,'QAbstractTableModel::dropMimeData()'],['https://doc.qt.io/qt-5/qconcatenatetablesproxymodel.html#dropMimeData',1,'QConcatenateTablesProxyModel::dropMimeData()'],['https://doc.qt.io/qt-5/qidentityproxymodel.html#dropMimeData',1,'QIdentityProxyModel::dropMimeData()'],['https://doc.qt.io/qt-5/qsortfilterproxymodel.html#dropMimeData',1,'QSortFilterProxyModel::dropMimeData()']]],
  ['dtd_1014',['DTD',['https://doc.qt.io/qt-5/qxmlstreamreader.html#TokenType-enum',1,'QXmlStreamReader']]],
  ['dtdname_1015',['dtdName',['https://doc.qt.io/qt-5/qxmlstreamreader.html#dtdName',1,'QXmlStreamReader']]],
  ['dtdpublicid_1016',['dtdPublicId',['https://doc.qt.io/qt-5/qxmlstreamreader.html#dtdPublicId',1,'QXmlStreamReader']]],
  ['dtdsystemid_1017',['dtdSystemId',['https://doc.qt.io/qt-5/qxmlstreamreader.html#dtdSystemId',1,'QXmlStreamReader']]],
  ['dual_1018',['Dual',['https://doc.qt.io/qt-5/qchar-obsolete.html#Joining-enum',1,'QChar']]],
  ['duala_1019',['Duala',['https://doc.qt.io/qt-5/qlocale.html#Language-enum',1,'QLocale']]],
  ['dumpobjectinfo_1020',['dumpObjectInfo',['https://doc.qt.io/qt-5/qobject-obsolete.html#dumpObjectInfo-1',1,'QObject::dumpObjectInfo()'],['https://doc.qt.io/qt-5/qobject.html#dumpObjectInfo',1,'QObject::dumpObjectInfo() const const']]],
  ['dumpobjecttree_1021',['dumpObjectTree',['https://doc.qt.io/qt-5/qobject.html#dumpObjectTree',1,'QObject::dumpObjectTree() const const'],['https://doc.qt.io/qt-5/qobject-obsolete.html#dumpObjectTree-1',1,'QObject::dumpObjectTree()']]],
  ['duployanscript_1022',['DuployanScript',['https://doc.qt.io/qt-5/qlocale.html#Script-enum',1,'QLocale']]],
  ['duration_1023',['duration',['https://doc.qt.io/qt-5/qsequentialanimationgroup.html#duration',1,'QSequentialAnimationGroup::duration()'],['https://doc.qt.io/qt-5/qvariantanimation.html#duration-prop',1,'QVariantAnimation::duration()'],['https://doc.qt.io/qt-5/qpauseanimation.html#duration-prop',1,'QPauseAnimation::duration()'],['https://doc.qt.io/qt-5/qtimeline.html#duration-prop',1,'QTimeLine::duration()'],['https://doc.qt.io/qt-5/qvariantanimation.html#duration-prop',1,'QVariantAnimation::duration()'],['https://doc.qt.io/qt-5/qabstractanimation.html#duration',1,'QAbstractAnimation::duration()'],['https://doc.qt.io/qt-5/qparallelanimationgroup.html#duration',1,'QParallelAnimationGroup::duration()'],['https://doc.qt.io/qt-5/qpauseanimation.html#duration-prop',1,'QPauseAnimation::duration()'],['https://doc.qt.io/qt-5/qtimeline.html#duration-prop',1,'QTimeLine::duration()'],['https://doc.qt.io/qt-5/qabstractanimation.html#duration-prop',1,'QAbstractAnimation::duration()']]],
  ['dutch_1024',['Dutch',['https://doc.qt.io/qt-5/qlocale.html#Language-enum',1,'QLocale']]],
  ['dx_1025',['dx',['https://doc.qt.io/qt-5/qline.html#dx',1,'QLine::dx()'],['https://doc.qt.io/qt-5/qlinef.html#dx',1,'QLineF::dx()']]],
  ['dy_1026',['dy',['https://doc.qt.io/qt-5/qline.html#dy',1,'QLine::dy()'],['https://doc.qt.io/qt-5/qlinef.html#dy',1,'QLineF::dy()']]],
  ['dynamiccast_1027',['dynamicCast',['https://doc.qt.io/qt-5/qsharedpointer.html#dynamicCast',1,'QSharedPointer']]],
  ['dynamicpropertychange_1028',['DynamicPropertyChange',['https://doc.qt.io/qt-5/qevent.html#Type-enum',1,'QEvent']]],
  ['dynamicpropertynames_1029',['dynamicPropertyNames',['https://doc.qt.io/qt-5/qobject.html#dynamicPropertyNames',1,'QObject']]],
  ['dynamicsortfilter_1030',['dynamicSortFilter',['https://doc.qt.io/qt-5/qsortfilterproxymodel.html#dynamicSortFilter-prop',1,'QSortFilterProxyModel::dynamicSortFilter()'],['https://doc.qt.io/qt-5/qsortfilterproxymodel.html#dynamicSortFilter-prop',1,'QSortFilterProxyModel::dynamicSortFilter() const const']]],
  ['dzongkha_1031',['Dzongkha',['https://doc.qt.io/qt-5/qlocale.html#Language-enum',1,'QLocale']]]
];
