name: Build
on:
  push:
    branches:
    - '*'
    tags:
    - '[0-9]*'
  pull_request:
    branches:
    - '*'
defaults:
  run:
    shell: bash
env:
  build_type: Release
jobs:
  linux:
    permissions:
      contents: write
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        qt_version: [5, 6]
        config:
        - { name: "GCC", cc: gcc, cxx: g++ }
        - { name: "clang", cc: clang, cxx: clang++ }
    env:
      cc:  ${{ matrix.config.cc }}
      cxx: ${{ matrix.config.cxx }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Update Packages
      run: sudo apt-get update

    - name: Install Dependencies
      run: |
        sudo apt-get install doxygen \
        ${{ matrix.qt_version == 5
        && 'qtbase5-dev qtbase5-doc-dev qttools5-dev'
        || 'libgl1-mesa-dev qt6-base-dev qt6-l10n-tools qt6-tools-dev qt6-tools-dev-tools'
        }}

    - name: Configure
      run: |
        options=(
          -D DBUSMENU_QT_VERSION=${{ matrix.qt_version }}
          -D CMAKE_BUILD_TYPE=${{ env.build_type }}
          -D CMAKE_INSTALL_PREFIX="/usr"
          -B build
        )
        cmake ${options[@]}

    - name: Build
      run: cmake --build build --config ${{ env.build_type }}

    - name: Upload Doxygen Documentation
      if: |
        matrix.qt_version == 5        &&
        matrix.config.cc  == 'clang'  &&
        github.ref_name   == 'master' &&
        github.event_name != 'pull_request'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: www
        publish_dir: ./build/html
        force_orphan: true
